# Generated by Django 5.1.2 on 2024-10-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.TextField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_age', models.IntegerField()),
                ('student_gender', models.TextField()),
                ('student_stream', models.TextField()),
            ],
        ),
    ]
